SELECT 'spend_pom' AS _q, TO_JSON_STRING(t) AS r FROM (
WITH raw AS (
  SELECT
    CASE WHEN REGEXP_CONTAINS(CAMPAIGN_NAME,'MLB_') THEN 'MLB'
         WHEN REGEXP_CONTAINS(CAMPAIGN_NAME,'MLM_') THEN 'MLM'
         WHEN REGEXP_CONTAINS(CAMPAIGN_NAME,'MLA_') THEN 'MLA'
         WHEN REGEXP_CONTAINS(CAMPAIGN_NAME,'MLC_') THEN 'MLC' END AS site_id,
    DATE_TRUNC(tim_day, MONTH) AS month_id, tim_day, COST_LC
  FROM `meli-bi-data.SBOX_MARKETING.BT_COST_GOOGLE_DAILY`
  WHERE account_id IN (5569824421,8633263195,2507743500,2902742417)
    AND tim_day >= DATE '2025-01-01'
  UNION ALL
  SELECT
    CASE WHEN REGEXP_CONTAINS(CAMPAIGN_NAME,'MLB_') THEN 'MLB'
         WHEN REGEXP_CONTAINS(CAMPAIGN_NAME,'MLM_') THEN 'MLM'
         WHEN REGEXP_CONTAINS(CAMPAIGN_NAME,'MLA_') THEN 'MLA'
         WHEN REGEXP_CONTAINS(CAMPAIGN_NAME,'MLC_') THEN 'MLC' END AS site_id,
    DATE_TRUNC(TIM_DAY, MONTH) AS month_id, TIM_DAY AS tim_day, COST_LC
  FROM `meli-bi-data.SBOX_MARKETING.BT_COST_FACEBOOK_DAILY`
  WHERE account_id IN (993018982140477,389685073604722,720409463494481,978457163701915,1049740082792804)
    AND TIM_DAY >= DATE '2025-01-01'
  UNION ALL
  SELECT
    CASE WHEN REGEXP_CONTAINS(CAMPAIGN_NAME,'MLB_') THEN 'MLB'
         WHEN REGEXP_CONTAINS(CAMPAIGN_NAME,'MLM_') THEN 'MLM'
         WHEN REGEXP_CONTAINS(CAMPAIGN_NAME,'MLA_') THEN 'MLA'
         WHEN REGEXP_CONTAINS(CAMPAIGN_NAME,'MLC_') THEN 'MLC' END AS site_id,
    DATE_TRUNC(EVENT_DATE, MONTH) AS month_id, EVENT_DATE AS tim_day, SPEND_LC AS COST_LC
  FROM `meli-bi-data.SBOX_MARKETING.BT_COST_TIKTOK_DAILY`
  WHERE advertiser_id IN (7296191154461114370,7356731484117663745,7520663504987226129)
    AND EVENT_DATE >= DATE '2025-01-01'
),
base AS (
  SELECT site_id, month_id,
    IF(month_id = DATE_TRUNC(CURRENT_DATE('America/Argentina/Buenos_Aires'), MONTH), 'mtd', 'hist') AS period,
    ROUND(SUM(COST_LC),2) AS cost_lc
  FROM raw WHERE site_id IN ('MLB','MLM','MLC','MLA')
  GROUP BY 1,2,3
)
SELECT * FROM base
UNION ALL
SELECT site_id, month_id, 'prev_mtd' AS period, ROUND(SUM(COST_LC),2) AS cost_lc
FROM raw
WHERE site_id IN ('MLB','MLM','MLC','MLA')
  AND month_id = DATE_SUB(DATE_TRUNC(CURRENT_DATE('America/Argentina/Buenos_Aires'), MONTH), INTERVAL 1 MONTH) AND tim_day <= DATE_ADD(DATE_SUB(DATE_TRUNC(CURRENT_DATE('America/Argentina/Buenos_Aires'), MONTH), INTERVAL 1 MONTH), INTERVAL GREATEST(1, LEAST(EXTRACT(DAY FROM CURRENT_DATE('America/Argentina/Buenos_Aires')) - 1, EXTRACT(DAY FROM LAST_DAY(DATE_SUB(DATE_TRUNC(CURRENT_DATE('America/Argentina/Buenos_Aires'), MONTH), INTERVAL 1 MONTH))))) - 1 DAY)
GROUP BY 1,2
ORDER BY site_id, month_id, period
) t
UNION ALL
SELECT 'data_freshness' AS _q, TO_JSON_STRING(t) AS r FROM (
-- MAX fecha disponible por tabla fuente ? para el tag "Datos cerrados hasta el X inclusive"
SELECT 'total_site'    AS tbl, FORMAT_DATE('%Y-%m-%d', MAX(DT)) AS max_dt
FROM `meli-bi-data.WHOWNER.BT_SC_TOTAL_SITE_AFILIADOS`
WHERE SIT_SITE_ID IN ('MLB','MLM','MLC','MLA')
UNION ALL
SELECT 'affiliate_base' AS tbl, FORMAT_DATE('%Y-%m-%d', MAX(CAST(DT AS DATE))) AS max_dt
FROM `meli-bi-data.WHOWNER.BT_SC_AFFILIATE_BASE`
WHERE SIT_SITE_ID IN ('MLB','MLM','MLC','MLA')
UNION ALL
SELECT 'attr_daily'    AS tbl, FORMAT_DATE('%Y-%m-%d', MAX(DATE(ORD_CREATED_DT))) AS max_dt
FROM `meli-bi-data.WHOWNER.BT_AFFI_SALES_ATTRIBUTION_DAILY`
WHERE SIT_SITE_ID IN ('MLB','MLM','MLC','MLA')
  AND ORD_STATUS = 'paid' AND SIT_SITE_ID = AFFILIATE_SIT_SITE_ID
UNION ALL
SELECT 'registrations' AS tbl, FORMAT_DATE('%Y-%m-%d', MAX(DATE(ds))) AS max_dt
FROM `meli-bi-data.SBOX_AFILIADOSCOREDATA.AFFILIATE_REGISTRATION_CHANNEL`
WHERE site_id IN ('MLB','MLM','MLC','MLA')
UNION ALL
SELECT 'landing'       AS tbl, FORMAT_DATE('%Y-%m-%d', MAX(DATE(ds))) AS max_dt
FROM `meli-bi-data.SBOX_AFILIADOSCOREDATA.MKT_REGISTRATION_JOURNEY`
WHERE page = 'landing'
) t
UNION ALL
SELECT 'mkt_context' AS _q, TO_JSON_STRING(t) AS r FROM (
SELECT
  KPI_ID,
  SIT_SITE_ID,
  PERIOD,
  FORMAT_DATE('%Y-%m-%d', DT_TO) AS dt_to,
  SUM(VIZ.vl_num) AS value,
  SUM(VIZ.vl_num_cp) AS value_cp
FROM `meli-bi-data.WHOWNER.DM_MKT_KPI_STORE`
WHERE KPI_ID IN ('NMV-UMM-MARKETPLACE', 'SESSIONS-AMPL')
  AND SIT_SITE_ID IN ('MLB', 'MLM', 'MLC', 'MLA')
  AND (PERIOD = 'MONTHLY' OR (PERIOD = 'MTD' AND DT_TO >= DATE_TRUNC(CURRENT_DATE(), MONTH) AND DT_TO <= CURRENT_DATE()))
  AND COMPARISON = 'PP'
  AND ((KPI_ID = 'NMV-UMM-MARKETPLACE' AND CURRENCY = 'LC')
    OR (KPI_ID = 'SESSIONS-AMPL' AND CURRENCY = '-1'))
  AND DT_TO >= DATE '2025-01-01'
GROUP BY 1,2,3,4
ORDER BY KPI_ID, SIT_SITE_ID, PERIOD, DT_TO
) t