WITH all_sales AS (
  SELECT SIT_SITE_ID, AFFILIATE_ID, DATE_TRUNC(ORD_CREATED_DT, MONTH) AS sale_month
  FROM `meli-bi-data.WHOWNER.BT_AFFI_SALES_ATTRIBUTION_DAILY`
  WHERE ORD_STATUS = 'paid' AND SIT_SITE_ID = AFFILIATE_SIT_SITE_ID
    AND SIT_SITE_ID IN ('MLB','MLM','MLC','MLA')
    AND ORD_CREATED_DT >= DATE '2024-01-01'
    AND ((ORD_CREATED_DT >= DATE '2026-04-01' AND NMV_ENIGMA_TOTAL_AMT_LC > 0)
      OR (ORD_CREATED_DT < DATE '2026-04-01' AND NMV_TD7DCALIB_TOTAL_AMT_LC > 0))
  GROUP BY 1,2,3
),
first_sale AS (SELECT SIT_SITE_ID, AFFILIATE_ID, MIN(sale_month) AS first_month FROM all_sales GROUP BY 1,2),
curr_7d AS (
  SELECT DISTINCT SIT_SITE_ID, AFFILIATE_ID
  FROM `meli-bi-data.WHOWNER.BT_AFFI_SALES_ATTRIBUTION_DAILY`
  WHERE ORD_CREATED_DT BETWEEN DATE_TRUNC(CURRENT_DATE('America/Argentina/Buenos_Aires'), MONTH) AND DATE_SUB(CURRENT_DATE('America/Argentina/Buenos_Aires'), INTERVAL 1 DAY)
    AND ORD_STATUS = 'paid' AND SIT_SITE_ID = AFFILIATE_SIT_SITE_ID
    AND SIT_SITE_ID IN ('MLB','MLM','MLC','MLA') AND NMV_ENIGMA_TOTAL_AMT_LC > 0
),
prev_7d AS (
  SELECT DISTINCT SIT_SITE_ID, AFFILIATE_ID
  FROM `meli-bi-data.WHOWNER.BT_AFFI_SALES_ATTRIBUTION_DAILY`
  WHERE ORD_CREATED_DT BETWEEN DATE_SUB(DATE_TRUNC(CURRENT_DATE('America/Argentina/Buenos_Aires'), MONTH), INTERVAL 1 MONTH) AND DATE_ADD(DATE_SUB(DATE_TRUNC(CURRENT_DATE('America/Argentina/Buenos_Aires'), MONTH), INTERVAL 1 MONTH), INTERVAL GREATEST(1, LEAST(EXTRACT(DAY FROM CURRENT_DATE('America/Argentina/Buenos_Aires')) - 1, EXTRACT(DAY FROM LAST_DAY(DATE_SUB(DATE_TRUNC(CURRENT_DATE('America/Argentina/Buenos_Aires'), MONTH), INTERVAL 1 MONTH))))) - 1 DAY)
    AND ORD_STATUS = 'paid' AND SIT_SITE_ID = AFFILIATE_SIT_SITE_ID
    AND SIT_SITE_ID IN ('MLB','MLM','MLC','MLA') AND NMV_ENIGMA_TOTAL_AMT_LC > 0
),
apr_full AS (SELECT DISTINCT SIT_SITE_ID, AFFILIATE_ID FROM all_sales WHERE sale_month = DATE_SUB(DATE_TRUNC(CURRENT_DATE('America/Argentina/Buenos_Aires'), MONTH), INTERVAL 1 MONTH)),
mar_full AS (SELECT DISTINCT SIT_SITE_ID, AFFILIATE_ID FROM all_sales WHERE sale_month = DATE_SUB(DATE_TRUNC(CURRENT_DATE('America/Argentina/Buenos_Aires'), MONTH), INTERVAL 2 MONTH)),
curr_flow AS (
  SELECT c.SIT_SITE_ID,
    COUNT(DISTINCT c.AFFILIATE_ID) AS active_aff,
    COUNT(DISTINCT IF(f.first_month = DATE_TRUNC(CURRENT_DATE('America/Argentina/Buenos_Aires'), MONTH), c.AFFILIATE_ID, NULL)) AS new_aff,
    COUNT(DISTINCT IF(f.first_month < DATE_TRUNC(CURRENT_DATE('America/Argentina/Buenos_Aires'), MONTH) AND a.AFFILIATE_ID IS NULL, c.AFFILIATE_ID, NULL)) AS recovered_aff
  FROM curr_7d c LEFT JOIN first_sale f USING (SIT_SITE_ID, AFFILIATE_ID)
  LEFT JOIN apr_full a USING (SIT_SITE_ID, AFFILIATE_ID) GROUP BY 1
),
curr_churn AS (
  SELECT a.SIT_SITE_ID, COUNT(DISTINCT IF(c.AFFILIATE_ID IS NULL, a.AFFILIATE_ID, NULL)) AS churned_aff
  FROM apr_full a LEFT JOIN curr_7d c USING (SIT_SITE_ID, AFFILIATE_ID) GROUP BY 1
),
prev_flow AS (
  SELECT p.SIT_SITE_ID,
    COUNT(DISTINCT p.AFFILIATE_ID) AS active_aff,
    COUNT(DISTINCT IF(f.first_month = DATE_SUB(DATE_TRUNC(CURRENT_DATE('America/Argentina/Buenos_Aires'), MONTH), INTERVAL 1 MONTH), p.AFFILIATE_ID, NULL)) AS new_aff,
    COUNT(DISTINCT IF(f.first_month < DATE_SUB(DATE_TRUNC(CURRENT_DATE('America/Argentina/Buenos_Aires'), MONTH), INTERVAL 1 MONTH) AND m.AFFILIATE_ID IS NULL, p.AFFILIATE_ID, NULL)) AS recovered_aff
  FROM prev_7d p LEFT JOIN first_sale f USING (SIT_SITE_ID, AFFILIATE_ID)
  LEFT JOIN mar_full m USING (SIT_SITE_ID, AFFILIATE_ID) GROUP BY 1
),
prev_churn AS (
  SELECT m.SIT_SITE_ID, COUNT(DISTINCT IF(p.AFFILIATE_ID IS NULL, m.AFFILIATE_ID, NULL)) AS churned_aff
  FROM mar_full m LEFT JOIN prev_7d p USING (SIT_SITE_ID, AFFILIATE_ID) GROUP BY 1
)
SELECT cf.SIT_SITE_ID, 'curr' AS period, cf.active_aff, cf.new_aff, cf.recovered_aff, cc.churned_aff
FROM curr_flow cf JOIN curr_churn cc USING (SIT_SITE_ID)
UNION ALL
SELECT pf.SIT_SITE_ID, 'prev' AS period, pf.active_aff, pf.new_aff, pf.recovered_aff, pc.churned_aff
FROM prev_flow pf JOIN prev_churn pc USING (SIT_SITE_ID)