SELECT
  KPI_ID,
  SIT_SITE_ID,
  PERIOD,
  FORMAT_DATE('%Y-%m-%d', DT_TO) AS dt_to,
  SUM(VIZ.vl_num) AS value,
  SUM(VIZ.vl_num_cp) AS value_cp
FROM `meli-bi-data.WHOWNER.DM_MKT_KPI_STORE`
WHERE KPI_ID IN ('NMV-UMM-MARKETPLACE', 'SESSIONS-AMPL')
  AND SIT_SITE_ID IN ('MLB', 'MLM', 'MLC', 'MLA')
  AND (PERIOD = 'MONTHLY' OR (PERIOD = 'MTD' AND DT_TO >= DATE_TRUNC(CURRENT_DATE(), MONTH) AND DT_TO <= CURRENT_DATE()))
  AND COMPARISON = 'PP'
  AND ((KPI_ID = 'NMV-UMM-MARKETPLACE' AND CURRENCY = 'LC')
    OR (KPI_ID = 'SESSIONS-AMPL' AND CURRENCY = '-1'))
  AND DT_TO >= DATE '2025-01-01'
GROUP BY 1,2,3,4
ORDER BY KPI_ID, SIT_SITE_ID, PERIOD, DT_TO