WITH all_sales AS (
  SELECT SIT_SITE_ID, AFFILIATE_ID, DATE(ORD_CREATED_DT) AS sale_date
  FROM `meli-bi-data.WHOWNER.BT_AFFI_SALES_ATTRIBUTION_DAILY`
  WHERE ORD_STATUS = 'paid' AND SIT_SITE_ID = AFFILIATE_SIT_SITE_ID
    AND SIT_SITE_ID IN ('MLB','MLM','MLC','MLA')
    AND ORD_CREATED_DT >= DATE_SUB(DATE_SUB(CURRENT_DATE('America/Argentina/Buenos_Aires'), INTERVAL 1 DAY), INTERVAL 61 DAY)
    AND ((ORD_CREATED_DT >= DATE '2026-04-01' AND NMV_ENIGMA_TOTAL_AMT_LC > 0)
      OR (ORD_CREATED_DT < DATE '2026-04-01' AND NMV_TD7DCALIB_TOTAL_AMT_LC > 0))
  GROUP BY 1,2,3
),
first_ever AS (
  SELECT SIT_SITE_ID, AFFILIATE_ID, MIN(DATE(ORD_CREATED_DT)) AS first_date
  FROM `meli-bi-data.WHOWNER.BT_AFFI_SALES_ATTRIBUTION_DAILY`
  WHERE ORD_STATUS = 'paid' AND SIT_SITE_ID = AFFILIATE_SIT_SITE_ID
    AND SIT_SITE_ID IN ('MLB','MLM','MLC','MLA') AND ORD_CREATED_DT >= DATE '2024-01-01'
    AND ((ORD_CREATED_DT >= DATE '2026-04-01' AND NMV_ENIGMA_TOTAL_AMT_LC > 0)
      OR (ORD_CREATED_DT < DATE '2026-04-01' AND NMV_TD7DCALIB_TOTAL_AMT_LC > 0))
  GROUP BY 1,2
),
win_curr AS (SELECT DISTINCT SIT_SITE_ID, AFFILIATE_ID FROM all_sales
  WHERE sale_date BETWEEN DATE_SUB(DATE_SUB(CURRENT_DATE('America/Argentina/Buenos_Aires'), INTERVAL 1 DAY), INTERVAL 29 DAY) AND DATE_SUB(CURRENT_DATE('America/Argentina/Buenos_Aires'), INTERVAL 1 DAY)),
win_prev AS (SELECT DISTINCT SIT_SITE_ID, AFFILIATE_ID FROM all_sales
  WHERE sale_date BETWEEN DATE_SUB(DATE_SUB(CURRENT_DATE('America/Argentina/Buenos_Aires'), INTERVAL 1 DAY), INTERVAL 59 DAY) AND DATE_SUB(DATE_SUB(CURRENT_DATE('America/Argentina/Buenos_Aires'), INTERVAL 1 DAY), INTERVAL 30 DAY)),
affiliates AS (
  SELECT SIT_SITE_ID, AFFILIATE_ID FROM win_curr
  UNION DISTINCT
  SELECT SIT_SITE_ID, AFFILIATE_ID FROM win_prev
)
SELECT a.SIT_SITE_ID,
  FORMAT_DATE('%Y-%m-%d', DATE_SUB(DATE_SUB(CURRENT_DATE('America/Argentina/Buenos_Aires'), INTERVAL 1 DAY), INTERVAL 29 DAY)) AS window_start,
  DATE_SUB(CURRENT_DATE('America/Argentina/Buenos_Aires'), INTERVAL 1 DAY) AS window_end,
  COUNT(DISTINCT IF(c.AFFILIATE_ID IS NOT NULL AND f.first_date >= DATE_SUB(DATE_SUB(CURRENT_DATE('America/Argentina/Buenos_Aires'), INTERVAL 1 DAY), INTERVAL 29 DAY), a.AFFILIATE_ID, NULL)) AS new_30d,
  COUNT(DISTINCT IF(c.AFFILIATE_ID IS NOT NULL AND p.AFFILIATE_ID IS NULL AND (f.first_date IS NULL OR f.first_date < DATE_SUB(DATE_SUB(CURRENT_DATE('America/Argentina/Buenos_Aires'), INTERVAL 1 DAY), INTERVAL 59 DAY)), a.AFFILIATE_ID, NULL)) AS recovered_30d,
  COUNT(DISTINCT IF(p.AFFILIATE_ID IS NOT NULL AND c.AFFILIATE_ID IS NULL, a.AFFILIATE_ID, NULL)) AS churned_30d,
  COUNT(DISTINCT c.AFFILIATE_ID) AS active_30d
FROM affiliates a
LEFT JOIN win_curr c USING (SIT_SITE_ID, AFFILIATE_ID)
LEFT JOIN win_prev p USING (SIT_SITE_ID, AFFILIATE_ID)
LEFT JOIN first_ever f USING (SIT_SITE_ID, AFFILIATE_ID)
GROUP BY 1,2,3